[package]
name = "rust-lapack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blas-src = { version = "0.9.0", features = ["openblas"] }
lapack = "0.19.0"
